---
- name: install apache server
  hosts: 172.31.95.28
  become: yes
  tasks:
    - name: install apache
      ansible.builtin.apt:
        name: apache2
        update_cache: yes
        state: present